const SET_PRODUCTS = "SET_PRODUCTS";
const ADD_PRODUCT_COMPARE = "ADD_PRODUCT_COMPARE";
const REMOVE_PRODUCT_COMPARE = "REMOVE_PRODUCT_COMPARE";
const SET_PRODUCT_COMPARE = "SET_PRODUCT_COMPARE";

const ADD_COMPARE_PROPERTY = "ADD_COMPARE_PROPERTY";
const REMOVE_COMPARE_PROPERTY = "REMOVE_COMPARE_PROPERTY";

export default {
  SET_PRODUCTS,
  ADD_PRODUCT_COMPARE,
  REMOVE_PRODUCT_COMPARE,
  SET_PRODUCT_COMPARE,
  ADD_COMPARE_PROPERTY,
  REMOVE_COMPARE_PROPERTY,
};
